services:

    #
    # Directors
    #
    elcodi.director.page:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.page'
            - '@elcodi.repository.page'
            - '@elcodi.factory.page'
