<?php

namespace Elcodi\Bundle\ProductBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * PrintSideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintSideRepository extends EntityRepository
{
}
