services:

    #
    # Services
    #
    elcodi_admin.form.location_selector_builder:
        class: Elcodi\Admin\GeoBundle\Form\LocationSelectorBuilder
        arguments:
            - "@elcodi.location_provider"
