services:

    #
    # Form Types
    #
    elcodi_admin.form_type.login:
        class: Elcodi\Admin\UserBundle\Form\Type\LoginType
        arguments:
            - "@router"
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_login }

    elcodi_admin.form_type.register:
        class: Elcodi\Admin\UserBundle\Form\Type\RegisterType
        arguments:
            - %elcodi.entity.customer.class%
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_register }

    elcodi_admin.form_type.profile:
        class: Elcodi\Admin\UserBundle\Form\Type\ProfileType
        calls:
            - [setFactory, ["@elcodi.factory.customer"]]
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_profile }

    elcodi_admin.form_type.password_remember:
        class: Elcodi\Admin\UserBundle\Form\Type\PasswordRememberType
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_password_remember }

    elcodi_admin.form_type.password_recover:
        class: Elcodi\Admin\UserBundle\Form\Type\PasswordRecoverType
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_password_recover }

    elcodi_admin.form_type.customer:
        class: Elcodi\Admin\UserBundle\Form\Type\CustomerType
        arguments:
            - %elcodi.entity.language.class%
        calls:
            - [setFactory, ["@elcodi.factory.customer"]]
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_customer }

    elcodi_admin.form_type.admin_user:
        class: Elcodi\Admin\UserBundle\Form\Type\AdminUserType
        calls:
            - [setFactory, ["@elcodi.factory.admin_user"]]
        tags:
            - { name: form.type, alias: elcodi_admin_user_form_type_admin_user }
