services:

    #
    # Factories
    #

    #
    # Factory for Authorization entities
    #
    elcodi_store.factory.authorization:
        class: Store\ConnectBundle\Factory\AuthorizationFactory
        calls:
            - [setEntityNamespace, ["%store.connect.entity.authorization.class%"]]
