services:

    #
    # Transformers for sitemap
    #
    elcodi_store.sitemap_transformer.product:
        class: Elcodi\Store\ProductBundle\Transformer\ProductTransformer
        arguments:
            - "@elcodi.entity_translator"
            - "@router"

    elcodi_store.sitemap_transformer.category:
        class: Elcodi\Store\ProductBundle\Transformer\CategoryTransformer
        arguments:
            - "@elcodi.entity_translator"
            - "@router"
