Elcodi\Bundle\CategoryBundle\Entity\DesignCategory:
    type: entity
    table: design_category
    repositoryClass: Elcodi\Bundle\CategoryBundle\Repository\CategoryRepository
    
    #manyToOne:
    #    category:
    #        targetEntity: Elcodi\Bundle\CategoryBundle\Entity\Category
    #        joinColumn:
    #            name: design_category_id
    #            referencedColumnName: id