services:

    #
    # Services
    #
    paymentsuite.bridge:
        class: Bridge\PaymentSuiteBridgeBundle\Services\PaymentBridge
        arguments:
            - "@elcodi.repository.order"
            - "@elcodi.wrapper.cart"
            - "@elcodi.converter.currency"
            - "@elcodi.name_resolver.purchasable"
