services:
           
    #
    # Form Event Listeners
    #  
    
    #
    # Article Product
    #
    elcodi.event_listener.article.form.article_product:
        class: Elcodi\Component\Article\EventListener\Form\ArticleProductFormEventListener
        arguments:            
            - '@elcodi.resolver.article_product_color'
            - '@elcodi.manager.article_product_print_sides'
    
    #
    # Article Product Print Sides
    #
    elcodi.event_listener.article.form.article_product_print_sides:
        class: Elcodi\Component\Article\EventListener\Form\ArticleProductPrintSidesFormEventListener
        arguments:
            - '@elcodi.factory.article_product_print_side'  
    
    #
    # Article Product Print Side
    #
    elcodi.event_listener.article.form.article_product_print_side:
        class: Elcodi\Component\Article\EventListener\Form\ArticleProductPrintSideFormEventListener
        arguments:
            - '@elcodi.factory.text_variant'
            - '@elcodi.factory.design_variant'