services:
           
    #
    # Form Event Listeners
    #  
    
    #
    # Article Product
    #
    elcodi.event_listener.article.form.article_product:
        class: Elcodi\Component\Article\EventListener\Form\ArticleProductFormEventListener
        arguments:            
            - '@elcodi.resolver.article_product_color'
            - '@elcodi.manager.article_product_print_sides'
            
    #
    # Printable Varaint
    #
    elcodi.event_listener.article.form.printable_variant:
        class: Elcodi\Component\Article\EventListener\Form\PrintableVariantFormEventListener
        arguments:            
            - '@elcodi.article.adapter.printable_size'
