services:

    #
    # Factories
    #    
            
    #
    # Factory for Article entities
    #
    elcodi.factory.article:
        class: Elcodi\Component\Article\Factory\ArticleFactory
        arguments:
            - "@elcodi.repository.product"
        calls:
            - [setEntityNamespace, ["%elcodi.entity.article.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]    
    
    #
    # Factory for ArticleProduct entities
    #
    elcodi.factory.article_product:
        class: Elcodi\Component\Article\Factory\ArticleProductFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.article_product.class%"]]
            
    #
    # Factory for ArticleProductPrintSide entities
    #
    elcodi.factory.article_product_print_side:
        class: Elcodi\Component\Article\Factory\ArticleProductPrintSideFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.article_product_print_side.class%"]]
            
    
