services:

    #
    # Factories
    #

    #
    # Factory for Article entities
    #
    elcodi.factory.article:
        class: Elcodi\Component\Article\Factory\ArticleFactory
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.article.class%"]]
            - [setUseStock, ["@elcodi.store_uses_stock"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
    
    #
    # Factory for Manufacturer entities
    #
    elcodi.factory.manufacturer:
        class: Elcodi\Component\Article\Factory\ManufacturerFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.manufacturer.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for Category entities
    #
    elcodi.factory.category:
        class: Elcodi\Component\Article\Factory\CategoryFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.category.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
