services:

    #
    # Event Listeners
    #
    elcodi_bridge.payment_suite.event_listener.cart_paid:
        class: Elcodi\Bridge\PaymentSuiteBridgeBundle\EventListener\CartPaidEventListener
        arguments:
            - "@elcodi.wrapper.cart"
            - "@elcodi.transformer.cart_order"
        tags:
            - { name: kernel.event_listener, event: payment.order.load, method: transformCartToOrder }

    elcodi_bridge.payment_suite.event_listener.order_to_paid:
        class: Elcodi\Bridge\PaymentSuiteBridgeBundle\EventListener\OrderToPaidEventListener
        arguments:
            - "@elcodi.order_payment_states_machine_manager"
            - "@elcodi.object_manager.order"
            - "@elcodi.object_manager.state_transition_machine_state_line"
        tags:
            - { name: kernel.event_listener, event: payment.order.success, method: setOrderToPaid }
