services:

    #
    # Visithor Bridge
    #
    visitor.environment_builder:
        class: Bridge\VisithorBridgeBundle\Environment\EnvironmentBuilder
        arguments:
            - "@elcodi.repository.customer"
            - "@elcodi.repository.admin_user"
