services:

    #
    # Services
    #
    elcodi_store.template_locator.page:
        class: Elcodi\Store\CoreBundle\Services\TemplateLocator
        arguments:
            engine: "@templating.engine.twig"
            bundles:
                - StoreOverrideBundle
                - StorePageBundle
                - StoreFallbackBundle
