services:

    #
    # Directors
    #
    elcodi.director.image:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.image'
            - '@elcodi.repository.image'
            - '@elcodi.factory.image'
