services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.media_image:
        class: Elcodi\Component\Media\Twig\ImageExtension
        public: false
        arguments:
            - '@router'
            - elcodi.route.image_resize
            - elcodi.route.image_view
            - %elcodi.image_generated_route_host%
        tags:
            - { name: twig.extension }
