services:

    #
    # Object Managers
    #
    elcodi.object_manager.category:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.category.class%

    elcodi.object_manager.section_category:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.section_category.class%
   
    elcodi.object_manager.product_category:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.product_category.class%
            
    elcodi.object_manager.design_category:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.design_category.class%

