services:

    #
    # Repositories
    #     

    #
    # Repository for entity category
    #
    elcodi.repository.category:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.category.class%
            
    #
    # Repository for entity section category
    #
    elcodi.repository.section_category:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.section_category.class%
            
    elcodi.repository.product_category:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product_category.class%
    
