services:

    #
    # Form Types
    #
    elcodi_admin.form_type.currency:
        class: Elcodi\Admin\CurrencyBundle\Form\Type\CurrencyType
        calls:
            - [setFactory, ["@elcodi.factory.currency"]]
        tags:
            - { name: form.type, alias: elcodi_admin_currency_form_type_currency }

    elcodi_admin.form_type.money:
        class: Elcodi\Admin\CurrencyBundle\Form\Type\MoneyType
        arguments:
            - "@elcodi.wrapper.default_currency"
            - %elcodi.entity.currency.class%
        tags:
            - { name: form.type, alias: money_object }
