services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.currency:
        class: Elcodi\Admin\CurrencyBundle\Builder\MenuBuilder
        arguments:
            - "@elcodi.factory.menu_node"
        tags:
            - { name: menu.builder, menu: admin, priority: 16 }
