services:

    #
    # Constraints
    #
    elcodi_admin.validator.minimum_money:
        class: Elcodi\Admin\ProductBundle\Validation\MinimumMoneyValidator
        tags:
            - { name: validator.constraint_validator, alias: minimum_money }
