services:

    #
    # Factories
    #

    #
    # Factory for Article entities
    #
    elcodi.factory.article:
        class: Elcodi\Component\Article\Factory\ArticleFactory
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.article.class%"]]
            - [setUseStock, ["@elcodi.store_uses_stock"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for Variant entities
    #
    elcodi.factory.article_variant:
        class: Elcodi\Component\Article\Factory\VariantFactory
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.article_variant.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for Pack entities
    #
    elcodi.factory.purchasable_pack:
        class: Elcodi\Component\Article\Factory\PackFactory
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.purchasable_pack.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for Manufacturer entities
    #
    elcodi.factory.manufacturer:
        class: Elcodi\Component\Article\Factory\ManufacturerFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.manufacturer.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]

    #
    # Factory for Category entities
    #
    elcodi.factory.category:
        class: Elcodi\Component\Article\Factory\CategoryFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.category.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
