services:

    #
    # Name resolvers
    #
    elcodi.image_resolver.abstract_article:
        class: Elcodi\Component\Article\ImageResolver\Abstracts\AbstractImageResolver
        arguments:
            - '@elcodi.resolver.image'

    elcodi.image_resolver.article:
        class: Elcodi\Component\Article\ImageResolver\ArticleImageResolver
        parent: elcodi.image_resolver.abstract_article
        tags:
            - { name: elcodi.purchasable_image_resolver }

    elcodi.image_resolver.article_variant:
        class: Elcodi\Component\Article\ImageResolver\VariantImageResolver
        parent: elcodi.image_resolver.abstract_article
        calls:
            - [ addPurchasableImageResolver, ['@elcodi.image_resolver.article'] ]
        tags:
            - { name: elcodi.purchasable_image_resolver }

    elcodi.image_resolver.purchasable_pack:
        class: Elcodi\Component\Article\ImageResolver\PackImageResolver
        parent: elcodi.image_resolver.abstract_article
        calls:
            - [ addPurchasableImageResolver, ['@elcodi.image_resolver.article'] ]
            - [ addPurchasableImageResolver, ['@elcodi.image_resolver.article_variant'] ]
        tags:
            - { name: elcodi.purchasable_image_resolver }

    elcodi.image_resolver.purchasable:
        class: Elcodi\Component\Article\ImageResolver\PurchasableImageResolver
