services:

    #
    # Directors
    #
    elcodi.director.rule:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.rule'
            - '@elcodi.repository.rule'
            - '@elcodi.factory.rule'
