Elcodi\Bundle\ProductBundle\Entity\PrintSide:
    type: entity
    table: print_side
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        enabled:
            type: boolean
        deletedAt:
            type: date
            nullable: true
            
    manyToOne:
        product:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Product
            inversedBy: printSides
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
                
        type:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\PrintSideType
            joinColumn:
                name: print_side_type_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
            
    lifecycleCallbacks: {  }
