Elcodi\Bundle\ProductBundle\Entity\PrintSide:
    type: entity
    table: print_side
    gedmo:
        soft_deleteable:
          field_name: deletedAt
          time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        enabled:
            type: boolean
        deletedAt:
            type: date
            nullable: true
            
    oneToOne:
        image:
            targetEntity: Elcodi\Component\Media\Entity\Interfaces\ImageInterface
            joinColumn:
                name: image_id
                referencedColumnName: id
                nullable: true
            
    manyToOne:
        product:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Interfaces\ProductInterface
            inversedBy: printSides
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
                
        type:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Interfaces\PrintSideTypeInterface
            joinColumn:
                name: print_side_type_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
                
    oneToMany:            
        areas:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Interfaces\PrintSideAreaInterface
            mappedBy: side
            cascade: [ "all" ]
            orphanRemoval: true
            
        sideProductColors:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Interfaces\PrintSideProductColorsInterface
            mappedBy: side
            cascade: [ "all" ]
            orphanRemoval: true
            
    lifecycleCallbacks: {  }
