Elcodi\Bundle\ProductBundle\Entity\ProductColors:
    type: entity
    table: product_colors
    repositoryClass: Elcodi\Bundle\ProductBundle\Repository\ProductColorsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    manyToOne:
        product:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Interfaces\ProductInterface
            inversedBy: colors
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
        color:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Interfaces\ProductColorInterface
            joinColumn:
                name: color_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"
                
    manyToMany:
        sizes:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Interfaces\ProductSizesInterface
            mappedBy: colors                        
                
    lifecycleCallbacks: {  }
