Elcodi\Bundle\ProductBundle\Entity\ProductVariant:
    type: entity
    table: product_variant
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sizeId:
            type: integer
            column: size_id
        colorId:
            type: integer
            column: color_id
        active:
            type: boolean
    manyToOne:
        product:
            targetEntity: Elcodi\Bundle\ProductBundle\Entity\Product
            inversedBy: variants
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"