services:

    #
    # Event Listeners
    #
    elcodi.event_listener.entity_translator_form:
        class: Elcodi\Component\EntityTranslator\EventListener\EntityTranslatorFormEventListener
        arguments:
            - '@elcodi.entity_translation_provider'
            - %elcodi.entity_translator_configuration%
            - '@elcodi.languages_iso_array'
            - %elcodi.entity_translator_language_master_locale%
            - %elcodi.entity_translator_language_fallback%
            - '@elcodi.entity_translator_changes'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: saveEntityTranslations }

    elcodi.entity_translator_form_event_listener:
        alias: elcodi.event_listener.entity_translator_form
