<?php

namespace Elcodi\Bundle\PrintableBundle\Repository;

/**
 * DesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignRepository extends \Doctrine\ORM\EntityRepository
{
}
