<?php

namespace Elcodi\Bundle\PrintableBundle\Repository;

/**
 * DesignVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
