<?php

namespace Elcodi\Bundle\PrintableBundle\Repository;

/**
 * PhotoVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
