<?php

namespace Elcodi\Bundle\PrintableBundle\Repository;

/**
 * PrintableVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintableVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
