<?php

namespace Elcodi\Bundle\PrintableBundle\Repository;

/**
 * TextVariantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextVariantRepository extends \Doctrine\ORM\EntityRepository
{
}
