knp_gaufrette:
    adapters:
        local:
            local:
                directory: '%kernel.root_dir%/../web/local'
                create: true
    filesystems:
        local:
            adapter: local
