snc_redis:
    clients:
        default:
            type: predis
            alias: metric
            options:
                profile: 2.8
            dsn: redis://localhost
            logging: false
