vich_uploader:
    db_driver: orm

    mappings:
        font_mapping:
            uri_prefix: /fonts
            upload_destination: '%kernel.root_dir%/../web/fonts'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true