Elcodi\Bundle\PrintableBundle\Entity\DesignVariant:
    type: entity
    table: design_variant
    repositoryClass: Elcodi\Bundle\PrintableBundle\Repository\DesignVariantRepository

    manyToOne:
        design:
            targetEntity: Elcodi\Bundle\PrintableBundle\Entity\Design
            joinColumn:
                name: design_id
                referencedColumnName: id