Elcodi\Bundle\PrintableBundle\Entity\PhotoVariant:
    type: entity
    table: photo_variant
    repositoryClass: Elcodi\Bundle\PrintableBundle\Repository\PhotoVariantRepository

    manyToOne:
        photo:
            targetEntity: Elcodi\Bundle\PrintableBundle\Entity\Photo
            joinColumn:
                name: photo_id
                referencedColumnName: id
