Elcodi\Bundle\PrintableBundle\Entity\TextVariant:
    type: entity
    table: text_variant
    repositoryClass: Elcodi\Bundle\PrintableBundle\Repository\TextVariantRepository

    manyToOne:
        text:
            targetEntity: Elcodi\Bundle\PrintableBundle\Entity\Text
            joinColumn:
                name: text_id
                referencedColumnName: id
            cascade:
                - persist

