services:

    #
    # Directors
    #
    elcodi.director.product:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.product'
            - '@elcodi.repository.product'
            - '@elcodi.factory.product'

    elcodi.director.product_color:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.product_color'
            - '@elcodi.repository.product_color'
            - '@elcodi.factory.product_color'
            
    elcodi.director.product_size:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.product_size'
            - '@elcodi.repository.product_size'
            - '@elcodi.factory.product_size'

