services:

    #
    # Event Listeners
    #
    elcodi.event_listener.product_print_side_form:
        class: Elcodi\Bundle\ProductBundle\EventListener\ProductPrintSideFormEventListener
        arguments:
            - '@elcodi.repository.print_side_type'
            
    elcodi.event_listener.product_colors_form:
        class: Elcodi\Bundle\ProductBundle\EventListener\ProductColorsFormEventListener
        arguments:
            - '@elcodi.repository.product_color'
            - '@elcodi.factory.product_colors'
            
    elcodi.event_listener.product_sizes_form:
        class: Elcodi\Bundle\ProductBundle\EventListener\ProductSizesFormEventListener
        arguments:
            - '@elcodi.repository.product_size'
            - '@elcodi.factory.product_sizes'
            
    elcodi.event_listener.product_print_sides_form:
        class: Elcodi\Bundle\ProductBundle\EventListener\ProductPrintSidesFormEventListener
        arguments:
            - '@elcodi.repository.print_side_type'
            - '@elcodi.factory.print_side'
            
