services:

    #
    # Repository for entity product
    #
    elcodi.repository.product:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product.class%
    
    #
    # Repository for entity print side type
    #
    elcodi.repository.print_side_type:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.print_side_type.class%
            
    #
    # Repository for entity product color
    #
    elcodi.repository.product_color:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product_color.class%
            
    #
    # Repository for entity product colors
    #
    elcodi.repository.product_colors:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product_colors.class%
            
    #
    # Repository for entity product size
    #
    elcodi.repository.product_size:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product_size.class%