services:

    #
    # Repository for entity product
    #
    elcodi.repository.product:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product.class%
            
    elcodi.repository.product_color:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product_color.class%
            
    elcodi.repository.product_size:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.product_size.class%
            