services:

    #
    # Twig Extensions
    #
    elcodi_admin.twig_extension.metric_intervals:
        class: Elcodi\Admin\MetricBundle\Twig\MetricIntervalsExtension
        arguments:
            - "@elcodi_admin.metric_intervals_resolver"
        tags:
            - { name: twig.extension }
