services:

    #
    # Event Listeners
    #
    elcodi.event_listener.update_cart_with_user:
        class: Elcodi\Component\User\EventListener\UpdateCartWithUserListener
        arguments:
            - '@elcodi.wrapper.cart'
            - '@elcodi.object_manager.cart'
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess  }

    elcodi.event_listener.update_last_login:
        class: Elcodi\Component\User\EventListener\UpdateLastLoginEventListener
        arguments:
            - '@elcodi.provider.manager'
            - '@elcodi.factory.datetime'
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: updateLastLogin}
