services:

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.user:
        class: Elcodi\Component\User\EventDispatcher\UserEventDispatcher
        parent: elcodi.event_dispatcher.abstract

    elcodi.event_dispatcher.password:
        class: Elcodi\Component\User\EventDispatcher\PasswordEventDispatcher
        parent: elcodi.event_dispatcher.abstract
