services:

    #
    # Factories
    #

    #
    # Factory for entity customer
    #
    elcodi.factory.customer:
        class: Elcodi\Component\User\Factory\CustomerFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.customer.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
            - [setGenerator, ['@elcodi.generator.random_string']]

    #
    # Factory for entity admin user
    #
    elcodi.factory.admin_user:
        class: Elcodi\Component\User\Factory\AdminUserFactory
        calls:
            - [setEntityNamespace, ["%elcodi.entity.admin_user.class%"]]
            - [setDateTimeFactory, ["@elcodi.factory.datetime"]]
            - [setGenerator, ['@elcodi.generator.random_string']]
