Elcodi\Component\StateTransitionMachine\Entity\StateLine:
    type: entity
    repositoryClass: Elcodi\Component\Cart\Repository\StateLineRepository
    table: state_line
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        description:
            column: description
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
