services:

    #
    # Services
    #
    elcodi_store.form.location_selector_builder:
        class: Store\GeoBundle\Form\LocationSelectorBuilder
        arguments:
            - "@elcodi.location_provider"
