Elcodi\Component\Rule\Entity\Rule:
    type: entity
    repositoryClass: Elcodi\Component\Rule\Repository\RuleRepository
    table: rule

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 64
            nullable: false
            unique: true
        expression:
            column: expression
            type: text
            nullable: false
