services:

    #
    # Directors
    #
    elcodi.director.state_transition_machine_state_line:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - '@elcodi.object_manager.state_transition_machine_state_line'
            - '@elcodi.repository.state_transition_machine_state_line'
            - '@elcodi.factory.state_transition_machine_state_line'
