services:

    #
    # Object Managers
    #
    elcodi.object_manager.state_transition_machine_state_line:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.state_transition_machine.state_line.class%
            
    elcodi.object_manager.state:
        parent: elcodi.abstract_manager
        arguments:
            - %elcodi.entity.state_transition_machine.state.class%
