services:

    #
    # Repositories
    #

    #
    # Repository for entity state_transition_machine_state_line
    #
    elcodi.repository.state_transition_machine_state_line:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.state_transition_machine.state_line.class%
            
    #
    # Repository for entity state
    #
    elcodi.repository.state:
        parent: elcodi.abstract_repository
        arguments:
            - %elcodi.entity.state_transition_machine.state.class%
