services:

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.hook_system:
        class: Elcodi\Component\Plugin\EventDispatcher\HookSystemEventDispatcher
        parent: elcodi.event_dispatcher.abstract
