services:

    #
    # Event Listeners
    #
    elcodi.event_listener.covert_cart_coupons_to_order_coupons:
        class: Elcodi\Component\CartCoupon\EventListener\ConvertCartCouponsToOrderCouponsEventListener
        arguments:
            - '@elcodi.transformer.cart_coupon_to_order_coupon'
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: createOrderCouponsByCartCoupons, priority: -16 }

    elcodi.event_listener.create_and_save_cart_coupon:
        class: Elcodi\Component\CartCoupon\EventListener\CreateAndSaveCartCouponEventListener
        arguments:
            - '@elcodi.manager.cart_coupon'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onapply, method: createAndSaveCartCoupon, priority: 1 }

    elcodi.event_listener.create_order_coupon_by_coupon:
        class: Elcodi\Component\CartCoupon\EventListener\CreateOrderCouponByCouponEventListener
        arguments:
            - '@elcodi.transformer.coupon_to_order_coupon'
        tags:
            - { name: kernel.event_listener, event: order_coupon.onapply, method: createOrderCouponByCoupon, priority: 0 }

    elcodi.event_listener.load_cart_coupon_amount:
        class: Elcodi\Component\CartCoupon\EventListener\LoadCartCouponAmountEventListener
        arguments:
            - '@elcodi.loader.cart_coupon_prices'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: refreshCouponAmount, priority: 6 }

    elcodi.event_listener.remove_cart_coupon:
        class: Elcodi\Component\CartCoupon\EventListener\RemoveCartCouponEventListener
        arguments:
            - '@elcodi.manager.cart_coupon'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onremove, method: removeCartCoupon, priority: 0 }

    elcodi.event_listener.try_automatic_coupons_application:
        class: Elcodi\Component\CartCoupon\EventListener\TryAutomaticCouponsApplicationEventListener
        arguments:
            - '@elcodi.applicator.automatic_coupon'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: tryAutomaticCoupons, priority: 16 }

    elcodi.event_listener.validate_cart_coupon:
        class: Elcodi\Component\CartCoupon\EventListener\ValidateCartCouponEventListener
        arguments:
            - '@elcodi.event_dispatcher.cart_coupon'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onapply, method: validateCoupon, priority: 16 }

    elcodi.event_listener.validate_coupon_duplication:
        class: Elcodi\Component\CartCoupon\EventListener\ValidateCouponDuplicationEventListener
        arguments:
            - '@elcodi.validator.duplicated_coupon'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onapply, method: validateDuplicatedCoupon, priority: 16 }

    elcodi.event_listener.validate_coupon:
        class: Elcodi\Component\CartCoupon\EventListener\ValidateCouponEventListener
        arguments:
            - '@elcodi.validator.cart_coupon'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.oncheck, method: validateCoupon, priority: 32 }

    elcodi.event_listener.validate_coupon_minimum_price:
        class: Elcodi\Component\CartCoupon\EventListener\ValidateCouponMinimumPriceEventListener
        arguments:
            - '@elcodi.validator.cart_coupon_minimum_price'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.oncheck, method: validateCartCouponMinimumPrice, priority: 0 }

    elcodi.event_listener.validate_coupon_rules:
        class: Elcodi\Component\CartCoupon\EventListener\ValidateCouponRulesEventListener
        arguments:
            - '@elcodi.validator.cart_coupon_rule'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.oncheck, method: validateCartCouponRules, priority: -16 }

    elcodi.event_listener.validate_coupons_from_cart:
        class: Elcodi\Component\CartCoupon\EventListener\ValidateCouponsFromCartEventListener
        arguments:
            - '@elcodi.validator.cart_coupon'
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: refreshCartCoupons, priority: 10 }

    elcodi.event_listener.validate_stackable_coupon:
        class: Elcodi\Component\CartCoupon\EventListener\ValidateStackableCouponsEventListener
        arguments:
            - '@elcodi.validator.stackable_coupon'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onapply, method: validateStackableCoupon, priority: 16 }

    elcodi.event_listener.update_cart_after_coupon_change:
        class: Elcodi\Component\CartCoupon\EventListener\CartUpdateAfterCouponChangeEventListener
        arguments:
            - '@elcodi.event_dispatcher.cart'
        tags:
            - { name: kernel.event_listener, event: cart_coupon.onapply, method: updateCart, priority: 0 }
            - { name: kernel.event_listener, event: cart_coupon.onremove, method: updateCart, priority: 0 }
