services:

    #
    # Directors
    #
    elcodi_store.director.authorization:
        class: Elcodi\Component\Core\Services\ObjectDirector
        lazy: true
        arguments:
            - "@store.connect.object_manager.authorization"
            - "@store.connect.repository.authorization"
            - "@elcodi_store.factory.authorization"
