Elcodi\Component\Article\Entity\Article:
    type: entity
    repositoryClass: Elcodi\Component\Article\Repository\ArticleRepository
    table: article

    manyToOne:
        principalVariant:
            targetEntity: Elcodi\Component\Article\Entity\Interfaces\VariantInterface
            joinColumn:
                name: principal_variant_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"

    oneToMany:
        variants:
            targetEntity: Elcodi\Component\Article\Entity\Interfaces\VariantInterface
            mappedBy: article
            cascade: [ "all" ]
            orphanRemoval: true

    manyToMany:
        attributes:
            targetEntity: Elcodi\Component\Attribute\Entity\Interfaces\AttributeInterface
            joinTable:
                name: article_attribute
                joinColumns:
                    article_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    attribute_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"

