services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.printable:
        class: Elcodi\Admin\PrintableBundle\Builder\MenuBuilder
        arguments:
            - "@elcodi.factory.menu_node"
        tags:
            - { name: menu.builder, menu: admin, priority: 36 }
