services:

    #
    # Event Dispatchers
    #
    elcodi.event_dispatcher.sitemap:
        class: Elcodi\Component\Sitemap\EventDispatcher\SitemapEventDispatcher
        parent: elcodi.event_dispatcher.abstract
