services:

    #
    # Sitemap Transformers
    #
    elcodi.sitemap_transformer.static:
        class: Elcodi\Component\Sitemap\Transformer\StaticRouteTransformer
        arguments:
            - '@router'
