services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.product:
        class: Elcodi\Component\Product\Twig\ProductOptionsResolverExtension
        public: false
        arguments:
            - '@elcodi.resolver.product_options'
        tags:
            - { name: twig.extension }

    elcodi.twig_extension.purchasable_name_resolver:
        class: Elcodi\Component\Product\Twig\PurchasableNameResolverExtension
        public: false
        arguments:
            - '@elcodi.name_resolver.purchasable'
        tags:
            - { name: twig.extension }

    elcodi.twig_extension.purchasable_image_resolver:
        class: Elcodi\Component\Product\Twig\PurchasableImageResolverExtension
        public: false
        arguments:
            - '@elcodi.image_resolver.purchasable'
        tags:
            - { name: twig.extension }
