services:

    #
    # Twig Extensions
    #
    elcodi.twig_extension.shipping:
        class: Elcodi\Component\Shipping\Twig\ShippingExtension
        public: false
        arguments:
            - '@elcodi.wrapper.shipping_methods'
        tags:
            - { name: twig.extension }
