services:

    #
    # Event listeners
    #
    elcodi_store.event_listener.shipping_appliance:
        class: Elcodi\Store\CartBundle\EventListener\ShippingApplianceEventListener
        arguments:
            - "@elcodi.event_dispatcher.cart"
            - "@elcodi.wrapper.shipping_methods"
            - "@elcodi.resolver.shipping"
        tags:
            - { name: kernel.event_listener, event: cart.onload, method: removeInvalidShippingMethod, priority: 8 }
            - { name: kernel.event_listener, event: cart.onload, method: loadCheapestShippingMethod, priority: 7 }

    elcodi_elcodi_store.event_listener.send_order_confirmation_email:
        class: Elcodi\Store\CartBundle\EventListener\SendOrderConfirmationEmailEventListener
        parent: store.abstract_email_sender_event_listener
        tags:
            - { name: kernel.event_listener, event: order.oncreated, method: sendOrderConfirmationEmail, priority: 0 }

    elcodi_elcodi_store.event_listener.send_order_shipped_email:
        class: Elcodi\Store\CartBundle\EventListener\SendOrderShippedEmailEventListener
        parent: store.abstract_email_sender_event_listener
        tags:
            - { name: kernel.event_listener, event: state_machine.order_shipping_states_machine.transition_ship, method: sendOrderShippedEmail, priority: 0 }
