#
# Store routes
#
store_core:
    resource: "@StoreCoreBundle/Resources/config/routing.yml"

store_product:
    resource: "@StoreProductBundle/Resources/config/routing.yml"

store_user:
    resource: "@StoreUserBundle/Resources/config/routing.yml"

store_cart:
    resource: "@StoreCartBundle/Resources/config/routing.yml"

store_cart_coupon:
    resource: "@StoreCartCouponBundle/Resources/config/routing.yml"

store_currency:
    resource: "@StoreCurrencyBundle/Resources/config/routing.yml"

store_page:
    resource: "@StorePageBundle/Resources/config/routing.yml"

store_login_check:
    path:  /login_check

store_logout:
    path: /logout

store_address:
    resource: "@StoreGeoBundle/Resources/config/routing.yml"

store_languages:
    resource: "@StoreLanguageBundle/Resources/config/routing.yml"

store_hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

store_hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

store_github_login:
    path: /login/check-github

store_paypal_login:
    path: /login/check-paypal
