#
# Store routes
#
store_routes:
    resource: "routing_store.yml"
    options:
        i18n: true

#
# Static pages
#
elcodi_page:
    resource: "@ElcodiPageBundle/Resources/config/routing.yml"
    prefix: /
    options:
        i18n: true

#
# Admin routes
#
admin_routes:
    resource: "routing_admin.yml"
    prefix: /%bamboo_admin_prefix%
    options:
        i18n: false

#
# API routes
#
api_routes:
    resource: "routing_api.yml"
    prefix: /%bamboo_api_prefix%
    options:
        i18n: false

#
# Media routes
#
media_routes:
    resource: "@ElcodiMediaBundle/Resources/config/routing.yml"
    options:
        i18n: false

#
# Plugin routes
#
plugin_routes:
    resource: .
    type: elcodi.routes.plugins

#
# Per project routes
# Add your routes in this file
#
elcodi_custom_routes:
    resource: "routing_local.yml"
    options:
        i18n: false
