#
# Per-project route definitions
#
# You can add your specific routes or override Elcodi's
#

## Example
#
#store_user:
#     resource: "@StoreUserBundle/Resources/config/routing.yml"
#     schemes: [ "HTTPS" ]
