Elcodi\Component\Article\Entity\Variant:
    type: entity
    repositoryClass: Elcodi\Component\Article\Repository\VariantRepository
    table: variant

    manyToOne:
        article:
            targetEntity: Elcodi\Component\Article\Entity\Interfaces\ArticleInterface
            inversedBy: variants
            joinColumn:
                name: article_id
                referencedColumnName: id
                nullable: false
                onDelete: "CASCADE"

    manyToMany:
        options:
            targetEntity: Elcodi\Component\Attribute\Entity\Interfaces\ValueInterface
            joinTable:
                name: variant_options
                joinColumns:
                    variant_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    option_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
