services:

    #
    # Form Types
    # 
    
    #
    # Article simple CartLine
    #
    elcodi_store.form_type.article_simple_cart_line:
        class: Elcodi\Store\ArticleBundle\Form\Type\CartLineType
        arguments:
            - '@elcodi_store.form_type.article_simple' 
        calls:
            - [setFactory, ["@elcodi.factory.article"]]
            - [setEntityTranslatorFormEventListener, ["@elcodi.entity_translator_form_event_listener"]]
        tags:
            - { name: form.type, alias: elcodi_store_cart_line_form_type_article }
    
    
    #
    # Article simple
    #
    elcodi_store.form_type.article_simple:
        class: Elcodi\Store\ArticleBundle\Form\Type\ArticleSimpleType
        arguments:
            - '@elcodi_store.form_type.article_simple_product' 
        calls:
            - [setFactory, ["@elcodi.factory.article"]]
            - [setEntityTranslatorFormEventListener, ["@elcodi.entity_translator_form_event_listener"]]
        tags:
            - { name: form.type, alias: elcodi_store_article_simple_form_type_article }
            
    #
    # Article simple Product
    #
    elcodi_store.form_type.article_simple_product:
        class: Elcodi\Store\ArticleBundle\Form\Type\ArticleSimpleProductType
        arguments:
            - %elcodi.entity.product.class%           
            - %elcodi.entity.product_colors.class%
            - '@elcodi.event_listener.article.form.article_product'
        calls:
            - [setFactory, ["@elcodi.factory.article_product"]]
        tags:
            - { name: form.type, alias: elcodi_store_article_simple_form_type_article_product }    
    
    # 
    # Article Product Print Sides
    #
    elcodi_admin.form_type.article_product_print_sides:
        class: Elcodi\Admin\ArticleBundle\Form\Type\ArticleProductPrintSidesType
        arguments:           
            - '@elcodi_admin.form_type.article_product_print_side'            
        calls:
            - [setFactory, ["@elcodi.factory.article_product"]]
        tags:
            - { name: form.type, alias: elcodi_admin_article_form_type_article_product_print_sides }
    
    #
    # Article Product Print Side
    #
    elcodi_admin.form_type.article_product_print_side:
        class: Elcodi\Admin\ArticleBundle\Form\Type\ArticleProductPrintSideType
        arguments:           
            - '@elcodi_admin.form_type.article_design_printable_variant'
            - '@elcodi_admin.form_type.article_text_printable_variant'
        calls:
            - [setFactory, ["@elcodi.factory.article_product_print_side"]]
        tags:
            - { name: form.type, alias: elcodi_admin_article_form_type_article_product_print_side }
            
    #
    # Design Printable Variant
    #
    elcodi_admin.form_type.article_design_printable_variant:
        class: Elcodi\Admin\ArticleBundle\Form\Type\DesignPrintableVariantType  
        arguments:
            - %elcodi.entity.design.class%
            - '@elcodi.event_listener.article.form.printable_variant'
        calls:
            - [setFactory, ["@elcodi.factory.design_variant"]]
        tags:
            - { name: form.type, alias: elcodi_admin_article_form_type_design_printable_variant }
            
    #
    # Text Printable Variant
    #
    elcodi_admin.form_type.article_text_printable_variant:
        class: Elcodi\Admin\ArticleBundle\Form\Type\TextPrintableVariantType  
        arguments:
            - %elcodi.entity.text.class%
            - '@elcodi_admin.form_type.text'
            - '@elcodi.event_listener.article.form.printable_variant'
        calls:
            - [setFactory, ["@elcodi.factory.text_variant"]]
        tags:
            - { name: form.type, alias: elcodi_admin_article_form_type_text_printable_variant }
         
    
    
