services:

    #
    # Menu builders
    #
    elcodi_admin.menu_builder.category:
        class: Elcodi\Admin\CategoryBundle\Builder\MenuBuilder
        arguments:
            - "@elcodi.factory.menu_node"
        tags:
            - { name: menu.builder, menu: admin, priority: 37 }
