services:

    #
    # Services
    #
    
    elcodi_admin.category_sorter:
        class: Elcodi\Admin\CategoryBundle\Services\CategorySorter
        arguments:
            - "@elcodi.repository.category"
            - "@elcodi.object_manager.category"
            - "@event_dispatcher"
